import { Roboto } from "next/font/google";
import "./globals.css";
import NavBar from "./Components/Navbar";

const roboto = Roboto({
  weight: ["100", "300"],
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={roboto.className}>
        <NavBar />
        {children}
      </body>
    </html>
  );
}
